### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by ulich** [fubarhouse/ansible-role-youtrack#11]
Thanks for your role. I get the following warnings when i run it with ansible 2.5.0:

```
hvm: [DEPRECATION WARNING]: The use of 'static' has been deprecated. Use
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion.
This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
```

This one is obviously a bug, `platforms` is defined twice:
```
 [WARNING]: While constructing a mapping from
/Users/timo/.ansible/roles/fubarhouse.jetbrains-youtrack/meta/main.yml, line 3,
column 3, found a duplicate dict key (platforms). Using last defined value
only.
```

**Comment by fubarhouse** [comment]
I was aiming to go through all my roles and fix this up around May, so I can get this done in the next couple of days. Thanks! :)

**Comment by fubarhouse** [comment]
Could you please review the above commit when you get a moment?

**Comment by ulich** [comment]
Sorry for the slow response. I now tested it. The 2 warnings are now gone. Thanks for the fast fix!
